server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 500

springdoc:
  swagger-ui:
    path=/:

spring:
  profiles:
    active: local
jwt:
  secret: qwerasdfzxcvdsafdsaffdasafdfdsafdsafdsafdsasfda
  access-token-expiration: 86400000
  refresh-token-expiration: 2592000000

aws:
  config:
    import: 'aws-secretsmanager:wequiz/aws/back'
  key:
    access-key: ${AWS_ACCESS_KEY}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    region: 'ap-northeast-2'
